/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1cNMjsV65MD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { useState } from 'react';



export function Main() {
  return (
    <div className="min-h-screen">
      <header className="flex items-center justify-between p-4 bg-orange-500 md:px-6 lg:px-8">
        <div className="flex items-center">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="mr-4" variant="ghost">
                <MenuIcon className="h-6 w-6" />
                MENÚ
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>Regalos</DropdownMenuItem>
              <DropdownMenuItem>Papelería</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <img
            src="1.png"
            alt="Omega Logo"
            width="70"
            height="60"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
        </div>
        <div className="relative flex items-center w-full max-w-md">
          <Input type="search" placeholder="¿Qué estás buscando hoy?" className="pl-8 pr-12" />
          <SearchIcon className="absolute right-4 h-6 w-6 text-muted-foreground" />
        </div>
        <div className="flex items-center space-x-4 md:space-x-6 lg:space-x-8">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <div className="cursor-pointer">
                <UserIcon className="h-6 w-6 text-white" />
                <DropdownMenuContent align="end" className="bg-white text-black px-2 py-1 rounded-md text-sm">
                  <DropdownMenuItem>
                    <Link href="#" className="flex items-center gap-2" prefetch={false}>
                      Iniciar sesión
                    </Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Link href="#" className="flex items-center gap-2" prefetch={false}>
                      Registrar
                    </Link>
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <div className="text-xs">
                      Acepto Términos y condiciones y autorizo ​​el tratamiento de mis datos personales conforme a la
                      política de privacidad y tratamiento de datos personales
                    </div>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </div>
            </DropdownMenuTrigger>
          </DropdownMenu>
          <Link href="#" className="text-white" prefetch={false}>
            <HeartIcon className="h-6 w-6" />
          </Link>
          <Link href="#" className="text-white" prefetch={false}>
            <ShoppingCartIcon className="h-6 w-6" />
          </Link>
        </div>
      </header>
      <div className="flex flex-col items-center justify-between p-2 bg-blue-500 md:flex-row md:px-4 lg:px-6">
        <div className="flex items-center space-x-4 md:space-x-6 lg:space-x-8">
          <Badge variant="default">Últimos Días</Badge>
          <Badge variant="default">Aprovecha esta promo!!</Badge>
          <Badge variant="default">¡Compra ya!</Badge>
        </div>
        <div className="flex items-center space-x-2">
          <div className="text-white text-sm md:text-base lg:text-lg">Termina en:</div>
          <div className="flex items-center space-x-1">
            <div className="p-1 bg-white text-blue-500 text-sm md:text-base lg:text-lg">05</div>
            <div className="p-1 bg-white text-blue-500 text-sm md:text-base lg:text-lg">02</div>
            <div className="p-1 bg-white text-blue-500 text-sm md:text-base lg:text-lg">38</div>
            <div className="p-1 bg-white text-blue-500 text-sm md:text-base lg:text-lg">21</div>
          </div>
        </div>
      </div>
      <section className="relative">
        <div className="flex items-center justify-between p-4 bg-gray-100 md:px-6 lg:px-8">
          <Button variant="ghost">
            <ChevronLeftIcon className="h-6 w-6" />
          </Button>
          <div className="flex items-center space-x-4 overflow-x-auto md:space-x-6 lg:space-x-8">
            <img
              src="descuento 1.png"
              alt="Product Image 1"
              width="150"
              height="200"
              style={{ aspectRatio: "150/200", objectFit: "cover" }}
            />
            <img
              src="descuento 2.png"
              alt="Product Image 2"
              width="290"
              height="200"
              style={{ aspectRatio: "150/200", objectFit: "cover" }}
            />
            <img
              src="descuento 3.png"
              alt="Product Image 3"
              width="150"
              height="200"
              style={{ aspectRatio: "150/200", objectFit: "cover" }}
            />
          </div>
          <Button variant="ghost">
            <ChevronRightIcon className="h-6 w-6" />
          </Button>
        </div>
      </section>
      <section className="p-4 md:px-6 lg:px-8">
  <h2 className="text-2xl font-bold md:text-3xl lg:text-4xl">Catálogo de Productos</h2>
  <div className="grid grid-cols-2 gap-4 md:grid-cols-4 lg:grid-cols-6">
    {[
      { imgSrc: "boligrafo.webp", name: "Bolígrafo", description: "3 tipos de colores x 12und, Marca BIG.", price: "$15.000" },
      { imgSrc: "borrador.webp", name: "Borrador", description: "Borrador de nata, Marca Pelikan.", price: "$1.000" },
      { imgSrc: "cuaderno1.jpg", name: "Cuadernos argollados", description: "Cuaderno 120 hojas, cuadriculado, Marca Triunfante.", price: "$8.000" },
      { imgSrc: "Lápices de colores.jpg", name: "Lápices de colores", description: "Caja x 50und, Marca Norma.", price: "$45.000" },
      { imgSrc: "Marcadores de Colores.avif", name: "Marcadores de Colores", description: "Bolsa de marcadores doble punta x 80und.", price: "$50.000" },
      { imgSrc: "lapiz.webp", name: "Lápices", description: "Lápiz, Marca FABER-CASTELL.", price: "$2.000" },
      { imgSrc: "Caja de Regalo Decorativa.jpg", name: "Caja de regalo decorativa", description: "Cajas de regalo en cartón.", price: "$1.500" },
      { imgSrc: "Cesta de chocolates.jpg", name: "Cesta de chocolates", description: "Diferentes tipos de chocolates típicos.", price: "$65.000" },
      { imgSrc: "Desayuno Romántico.jpg", name: "Desayuno romántico", description: "Desayunos para él o para ella.", price: "$65.000" },
      { imgSrc: "Papel de Envoltura.jpg", name: "Papel de envoltura", description: "Rollo de papel regalo para diferentes ocasiones.", price: "$1.500" },
      { imgSrc: "peluches.jpg", name: "Peluches", description: "Peluches en variedad.", price: "$40.00" },
      { imgSrc: "Taza Personalizada.jpg", name: "Taza personalizada", description: "Tazas a tu gusto.", price: "$15.000" }
    ].map((product, index) => (
      <Card key={index} className="flex flex-col">
        <CardContent className="flex flex-col h-full justify-between">
          <img
            src={product.imgSrc}
            alt={product.name}
            width="150"
            height="150"
            style={{ aspectRatio: "150/150", objectFit: "cover" }}
          />
          <div className="flex-grow flex flex-col justify-between">
            <div className="flex flex-col justify-between h-40"> {/* Fija la altura del bloque de texto */}
              <h3 className="text-lg font-bold md:text-xl lg:text-2xl text-center">{product.name}</h3>
              <p className="text-muted-foreground text-sm md:text-base lg:text-lg text-center">{product.description}</p>
              <p className="text-lg font-semibold mt-2 text-center">{product.price}</p>
            </div>
            <div className="flex justify-center mt-4 space-x-2">
              <button className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700">
                Añadir al carrito
              </button>
              <button className="px-4 py-2 text-sm font-medium text-white bg-gray-600 rounded-md hover:bg-gray-700">
                Ver detalles
              </button>
            </div>
          </div>
        </CardContent>
      </Card>
    ))}
  </div>
</section>


<section className="relative">
  <div className="flex items-center justify-between p-4 bg-gray-100 md:px-6 lg:px-8">
    <Button variant="ghost">
      <ChevronLeftIcon className="h-6 w-6" />
    </Button>
    <div className="flex items-center space-x-4 overflow-x-auto md:space-x-6 lg:space-x-8">
      <img
        src="marca1.png"
        alt="Brand 1"
        width="80"
        height="80"
        style={{ aspectRatio: "1/1", objectFit: "contain" }}
      />
      <img
        src="marca 2.jpg"
        alt="Brand 2"
        width="80"
        height="80"
        style={{ aspectRatio: "1/1", objectFit: "contain" }}
      />
      <img
        src="marca3.png"
        alt="Brand 3"
        width="80"
        height="80"
        style={{ aspectRatio: "1/1", objectFit: "contain" }}
      />
      <img
        src="marca4.png"
        alt="Brand 4"
        width="80"
        height="80"
        style={{ aspectRatio: "1/1", objectFit: "contain" }}
      />
      <img
        src="marca5.png"
        alt="Brand 5"
        width="80"
        height="80"
        style={{ aspectRatio: "1/1", objectFit: "contain" }}
      />
      <img
        src="marca6.png"
        alt="Brand 6"
        width="80"
        height="80"
        style={{ aspectRatio: "1/1", objectFit: "contain" }}
      />
    </div>
    <Button variant="ghost">
      <ChevronRightIcon className="h-6 w-6" />
    </Button>
  </div>
</section>

      
      <footer className="bg-black text-white p-4 md:px-6 lg:px-8 w-full">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <h3 className="text-lg font-bold mb-2">Contáctanos</h3>
            <ul className="space-y-1">
              <li>Teléfono: 3105751123</li>
              <li>Instagram: https://www.instagram.com/detalles.omega?igsh=MXVvM3lxMTViY2tzMw==</li>
              <li>Dirección: Carrera 100 #139, Bogotá, Colombia</li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-2">Conócenos</h3>
            <ul className="space-y-1">
              <li>En Omega, combinamos tradición y sostenibilidad para ofrecer productos de la más alta calidad, respaldados por un equipo comprometido con la excelencia y la innovación. Nuestra pasión por lo que hacemos nos impulsa a superar las expectativas de nuestros clientes cada día.</li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-2">Políticas</h3>
            <ul className="space-y-1">
              <li>
                <Link href="#" className="underline" prefetch={false}>
                  Términos y Condiciones
                </Link>
              </li>
              <li>
                <Link href="#" className="underline" prefetch={false}>
                  Política de Privacidad
                </Link>
              </li>
              <li>
                <Link href="#" className="underline" prefetch={false}>
                  Política de Cookies
                </Link>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-2">Medios de Pago</h3>
            <div className="flex items-center space-x-4">
              <img
                src="pago1.png"
                alt="Visa"
                width="50"
                height="30"
                style={{ aspectRatio: "50/30", objectFit: "cover" }}
              />
              <img
                src="pago2.jpg"
                alt="Mastercard"
                width="50"
                height="30"
                style={{ aspectRatio: "50/30", objectFit: "cover" }}
              />
              <img
                src="pago5.png"
                alt="American Express"
                width="50"
                height="30"
                style={{ aspectRatio: "50/30", objectFit: "cover" }}
              />
          
            </div>
          </div>
        </div>
      </footer>
      <div className="fixed bottom-0 left-0 right-0 bg-black text-white p-4 flex justify-between items-center">
        <p className="text-sm">
          Usamos cookies para mejorar tu experiencia. Conoce nuestra política de{" "}
          <Link href="#" className="underline" prefetch={false}>
            cookies
          </Link>{" "}
          y de{" "}
          <Link href="#" className="underline" prefetch={false}>
            privacidad
          </Link>
          .
        </p>
        <Button variant="outline" className="bg-orange-500 text-white text-sm">
          ACEPTAR
        </Button>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function HeartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}



